const API = "./api/quote-records";
const state = { records: [], search: "", status: "", payment: "", sort: "newest", view: "jobs", layout: "board", selected: null };
const $ = (selector) => document.querySelector(selector);
const currency = (value) => new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(Number(value) || 0);
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[character]);
const normalise = (record) => {
  const job = record.job && typeof record.job === "object" ? record.job : {};
  return { ...record, job: { number: job.number || record.quoteNumber || "", detail: job.detail || job.description || "", quote: Number(job.quote ?? String(record.totalQuote || "").replace(/[^0-9.-]/g, "")) || 0, markup: Number(job.markup) || 0, status: job.status || record.jobStage || "quoted", payment: job.payment || "pending", referral: job.referral || "pending", invoiceNumber: job.invoiceNumber || "", invoiceDate: job.invoiceDate || "", scheduledDate: job.scheduledDate || "" } };
};
async function request(path = "", options = {}) { const response = await fetch(`${API}${path}`, { headers: { "Content-Type":"application/json", ...(options.headers || {}) }, ...options }); if (!response.ok) throw new Error(await response.text()); return response.status === 204 ? null : response.json(); }
async function loadRecords() { $("#sync-state").innerHTML = "<span></span> Syncing shared data"; try { state.records = (await request()).map(normalise); $("#sync-state").innerHTML = "<span></span> Shared data is up to date"; render(); } catch (error) { $("#sync-state").innerHTML = "<span></span> Offline — unable to sync"; render(); console.warn(error); } }
function filtered() { const term = state.search.trim().toLowerCase(); const items = state.records.filter((record) => { const j = record.job; return (!state.status || j.status === state.status) && (!state.payment || j.payment === state.payment) && (!term || [j.number,record.customerName,record.address,j.detail].some((value) => String(value || "").toLowerCase().includes(term))); }); return items.sort((a,b) => state.sort === "address" ? String(a.address).localeCompare(String(b.address)) : state.sort === "quote-high" ? b.job.quote-a.job.quote : state.sort === "status" ? a.job.status.localeCompare(b.job.status) : new Date(b.submittedAt)-new Date(a.submittedAt)); }
function tag(value) { const label = value === "not-applicable" ? "Not applicable" : value.charAt(0).toUpperCase() + value.slice(1); return `<span class="tag ${escapeHtml(value)}">${escapeHtml(label)}</span>`; }
function renderJobs() { const items = filtered(); $("#jobs-body").innerHTML = items.map((record) => { const j = record.job; return `<tr data-id="${escapeHtml(record.id)}"><td>${escapeHtml(j.number)}</td><td class="address">${escapeHtml(record.address)}</td><td class="detail">${escapeHtml(j.detail || "—")}</td><td class="money">${currency(j.quote)}</td><td>${j.markup ? `${j.markup}%` : "—"}</td><td>${tag(j.status)}</td><td>${tag(j.payment)}</td><td>${tag(j.referral)}</td><td>${escapeHtml(j.invoiceNumber || "—")}</td><td>${escapeHtml(j.invoiceDate || "—")}</td></tr>`; }).join(""); $("#jobs-empty").style.display = items.length ? "none" : "block"; $("#result-count").textContent = `${items.length} job${items.length === 1 ? "" : "s"}`; $("#quote-total").textContent = currency(items.reduce((sum, record) => sum + record.job.quote, 0)); $("#invoice-total").textContent = currency(items.filter((record) => record.job.invoiceNumber).reduce((sum, record) => sum + record.job.quote, 0)); }
function renderBoard() { const stages = ["quoted", "confirmed", "scheduled", "completed"]; const labels = { quoted:"Quotes", confirmed:"Confirmed", scheduled:"Scheduled", completed:"Completed" }; const records = filtered(); $("#job-board").innerHTML = stages.map((stage) => { const jobs = records.filter((record) => record.job.status === stage); return `<section class="board-column board-${stage}"><header class="board-head"><strong>${labels[stage]} <span>${jobs.length}</span></strong><button class="lane-add" type="button" data-new-job-stage="${stage}">＋ Add job</button></header><div class="board-dropzone" data-stage="${stage}">${jobs.length ? jobs.map((record) => `<article class="board-card" draggable="true" data-job-id="${escapeHtml(record.id)}"><div class="board-card-top"><span>⠿ &nbsp;${escapeHtml(record.job.number)}</span><span>✎</span></div><div class="board-card-content"><p class="board-card-address">${escapeHtml(record.address)}</p><p class="board-card-detail">${escapeHtml(record.job.detail || "No job detail")}</p><div class="board-card-bottom"><span>Quote</span><strong>${currency(record.job.quote)}</strong></div><div class="board-card-bottom"><span>Payment</span><strong>${escapeHtml(record.job.payment || "Pending")}</strong></div><div class="board-card-bottom"><span>Referral</span><strong>${escapeHtml(record.job.referral || "—")}</strong></div></div></article>`).join("") : `<div class="board-empty">Drop card here</div>`}</div><button class="lane-add lane-add-bottom" type="button" data-new-job-stage="${stage}">＋ Add job</button></section>`; }).join(""); }
function renderCalendar() { const scheduled = state.records.filter((record) => record.job.scheduledDate).sort((a,b) => String(a.job.scheduledDate).localeCompare(String(b.job.scheduledDate))); $("#calendar-grid").innerHTML = scheduled.length ? scheduled.map((record) => `<article class="calendar-item"><strong>${escapeHtml(record.job.number)} · ${escapeHtml(record.address)}</strong><span>${escapeHtml(record.job.scheduledDate)} · ${escapeHtml(record.job.detail || "Job scheduled")}</span></article>`).join("") : `<div class="empty" style="display:block">Add a scheduled date to a job to see it here.</div>`; }
function renderClients() { const clients = [...new Map(state.records.filter((r) => r.customerName && r.customerName !== "-").map((r) => [r.customerName, r])).values()]; $("#client-list").innerHTML = clients.map((record) => `<article class="client-item"><strong>${escapeHtml(record.customerName)}</strong><span>${escapeHtml(record.phone || "No phone")} · ${escapeHtml(record.address || "No address")}</span></article>`).join("") || `<div class="empty" style="display:block">Clients will appear when quotes are saved.</div>`; }
function renderTasks() { const active = state.records.filter((record) => !["completed"].includes(record.job.status)); $("#task-list").innerHTML = active.map((record) => `<article class="task-item"><strong>${escapeHtml(record.job.number)} · ${escapeHtml(record.address)}</strong><span>${escapeHtml(record.job.detail || "No job detail added")}</span><div class="task-meta"><em>${escapeHtml(record.job.status === "quoted" ? "Follow up quote" : record.job.status === "confirmed" ? "Schedule the job" : "Complete scheduled work")}</em><b>Quote ${currency(record.job.quote)}</b></div></article>`).join("") || `<div class="empty" style="display:block">No active tasks.</div>`; }
function renderReports() { const all = state.records; const paid = all.filter((record) => record.job.payment === "paid"); $("#report-grid").innerHTML = `<article class="report-card"><span>Total quotations</span><strong>${currency(all.reduce((sum, r) => sum + r.job.quote, 0))}</strong></article><article class="report-card"><span>Paid jobs</span><strong>${paid.length}</strong></article><article class="report-card"><span>Completed jobs</span><strong>${all.filter((r) => r.job.status === "completed").length}</strong></article>`; }
function render() { renderJobs(); renderBoard(); renderCalendar(); renderClients(); renderTasks(); renderReports(); renderQuotes(); }
async function moveJob(id, status) { const record = state.records.find((item) => item.id === id); if (!record || record.job.status === status) return; const previous = record; const updated = normalise({ ...record, jobStage: status, job: { ...record.job, status } }); state.records = state.records.map((item) => item.id === id ? updated : item); render(); try { const saved = normalise(await request(`?id=${encodeURIComponent(id)}`, { method:"PATCH", body:JSON.stringify(updated) })); state.records = state.records.map((item) => item.id === id ? saved : item); render(); } catch (error) { state.records = state.records.map((item) => item.id === id ? previous : item); render(); window.alert("The job could not be moved in the shared tracker. Please try again."); console.warn(error); } }
function openDrawer(record = null, defaultStage = "quoted") { state.selected = record; const j = record?.job || {}; $("#drawer-title").textContent = record ? j.number || "Edit job" : "New job"; $("#record-id").value = record?.id || ""; $("#job-number").value = j.number || `J-${String(Date.now()).slice(-5)}`; $("#job-client").value = record?.customerName && record.customerName !== "-" ? record.customerName : ""; $("#job-address").value = record?.address && record.address !== "-" ? record.address : ""; $("#job-detail").value = j.detail || ""; $("#job-quote").value = j.quote || ""; $("#job-markup").value = j.markup || ""; $("#job-status").value = j.status || defaultStage; $("#job-payment").value = j.payment || "pending"; $("#job-referral").value = j.referral || "pending"; $("#job-invoice").value = j.invoiceNumber || ""; $("#job-invoice-date").value = j.invoiceDate || ""; $("#job-scheduled-date").value = j.scheduledDate || ""; $("#drawer").classList.add("open"); $("#drawer").setAttribute("aria-hidden", "false"); }
function closeDrawer() { $("#drawer").classList.remove("open"); $("#drawer").setAttribute("aria-hidden", "true"); }
function formRecord() { const base = state.selected ? { ...state.selected } : { id: crypto.randomUUID(), recordType:"general", sector:"General", submittedAt:new Date().toISOString(), phone:"", email:"", subtotalExGst:"$0.00", gstTotal:"$0.00", blindItems:[], curtainItems:[] }; const quote = Number($("#job-quote").value) || 0; return { ...base, customerName: $("#job-client").value.trim() || "-", address: $("#job-address").value.trim(), quoteNumber: $("#job-number").value.trim(), totalQuote: currency(quote), jobStage: $("#job-status").value, job:{ number:$("#job-number").value.trim(), detail:$("#job-detail").value.trim(), quote, markup:Number($("#job-markup").value)||0, status:$("#job-status").value, payment:$("#job-payment").value, referral:$("#job-referral").value, invoiceNumber:$("#job-invoice").value.trim(), invoiceDate:$("#job-invoice-date").value, scheduledDate:$("#job-scheduled-date").value } }; }
async function saveJob(event) { event.preventDefault(); const record = formRecord(); try { const saved = normalise(await request(state.selected ? `?id=${encodeURIComponent(record.id)}` : "", { method: state.selected ? "PATCH" : "POST", body: JSON.stringify(record) })); state.records = state.selected ? state.records.map((item) => item.id === saved.id ? saved : item) : [saved, ...state.records]; closeDrawer(); render(); } catch (error) { window.alert("Unable to save this job to the shared tracker. Check the cloud connection and try again."); console.warn(error); } }
function renderQuotes() { $("#quotes-body").innerHTML = state.records.map((record) => `<tr data-id="${escapeHtml(record.id)}"><td>${escapeHtml(record.job.number)}</td><td>${escapeHtml(record.address)}</td><td>${escapeHtml(record.job.detail || "—")}</td><td>${currency(record.job.quote)}</td><td>${tag(record.job.status)}</td></tr>`).join("") || `<tr><td colspan="5">No saved quotes yet.</td></tr>`; $("#invoices-body").innerHTML = state.records.filter((record) => record.job.invoiceNumber || record.job.status === "completed").map((record) => `<tr data-id="${escapeHtml(record.id)}"><td>${escapeHtml(record.job.invoiceNumber || "—")}</td><td>${escapeHtml(record.job.number)}</td><td>${escapeHtml(record.address)}</td><td>${escapeHtml(record.job.invoiceDate || "—")}</td><td>${tag(record.job.payment)}</td><td>${currency(record.job.quote)}</td></tr>`).join("") || `<tr><td colspan="6">No invoices recorded yet.</td></tr>`; }
function setView(view) { state.view = view; document.querySelectorAll(".nav-link[data-view]").forEach((button) => button.classList.toggle("active", button.dataset.view === view)); document.querySelectorAll(".view").forEach((section) => section.classList.toggle("active", section.id === `view-${view}`)); const labels = { jobs:["Job Board","All work in one shared job register."],calendar:["Calendar","Scheduled jobs from the shared register."],clients:["Clients","All clients from saved quotes."],quotes:["Quotes","Every quote in the shared register."],invoices:["Invoices","Completed or invoiced jobs from the shared register."],tasks:["Tasks","The next actions for active jobs."],reports:["Reports","Live job and payment summaries."],settings:["Settings","Shared tracker settings."] }; $("#page-title").textContent = labels[view][0]; $("#page-description").textContent = labels[view][1]; $("#add-job").style.display = view === "jobs" ? "inline-block" : "none"; if (view === "quotes" || view === "invoices") renderQuotes(); }
document.addEventListener("DOMContentLoaded", () => { $("#search").addEventListener("input", (e) => { state.search = e.target.value; render(); }); $("#filter-status").addEventListener("change", (e) => { state.status=e.target.value; render(); }); $("#filter-payment").addEventListener("change", (e) => { state.payment=e.target.value; render(); }); $("#sort").addEventListener("change", (e) => { state.sort=e.target.value; render(); }); $("#jobs-body").addEventListener("click", (e) => { const row=e.target.closest("tr[data-id]"); if(row) openDrawer(state.records.find((record)=>record.id===row.dataset.id)); }); $("#add-job").addEventListener("click",()=>openDrawer()); $("#close-drawer").addEventListener("click",closeDrawer); $("#cancel-edit").addEventListener("click",closeDrawer); $("#job-form").addEventListener("submit",saveJob); $("#refresh-button").addEventListener("click",loadRecords); document.querySelectorAll(".nav-link[data-view]").forEach((button)=>button.addEventListener("click",()=>setView(button.dataset.view))); loadRecords(); window.setInterval(loadRecords, 30000); });
document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll("[data-layout]").forEach((button) => button.addEventListener("click", () => {
    state.layout = button.dataset.layout;
    document.querySelectorAll("[data-layout]").forEach((item) => item.classList.toggle("active", item === button));
    $("#table-layout").classList.toggle("active", state.layout === "table");
    $("#board-layout").classList.toggle("active", state.layout === "board");
  }));
  $("#job-board").addEventListener("dragstart", (event) => {
    const card = event.target.closest("[data-job-id]");
    if (!card) return;
    card.classList.add("dragging");
    event.dataTransfer.effectAllowed = "move";
    event.dataTransfer.setData("text/plain", card.dataset.jobId);
  });
  $("#job-board").addEventListener("dragend", () => document.querySelectorAll(".drag-over").forEach((zone) => zone.classList.remove("drag-over")));
  $("#job-board").addEventListener("dragover", (event) => {
    const zone = event.target.closest("[data-stage]");
    if (!zone) return;
    event.preventDefault();
    zone.classList.add("drag-over");
  });
  $("#job-board").addEventListener("dragleave", (event) => {
    const zone = event.target.closest("[data-stage]");
    if (zone && !zone.contains(event.relatedTarget)) zone.classList.remove("drag-over");
  });
  $("#job-board").addEventListener("drop", (event) => {
    const zone = event.target.closest("[data-stage]");
    if (!zone) return;
    event.preventDefault();
    zone.classList.remove("drag-over");
    moveJob(event.dataTransfer.getData("text/plain"), zone.dataset.stage);
  });
  $("#job-board").addEventListener("click", (event) => { const add = event.target.closest("[data-new-job-stage]"); if (add) { openDrawer(null, add.dataset.newJobStage); return; } const card = event.target.closest(".board-card[data-job-id]"); if (card) openDrawer(state.records.find((record) => record.id === card.dataset.jobId)); });
});
